kind: pipeline
name: default

steps:
    - name: check-links
      image: node:14-alpine
      commands:
          - npm i -g markdown-link-check
          - find . -name \*.md -not -path "./node_modules/*"

trigger:
    event:
        - pull_request
