---
kind: pipeline
type: docker
name: Java Maven Deploy

trigger:
  branch:
    - master
  event:
    - push

steps:
  - name: testing
    image: maven
    commands:
      - mvn test
  - name: settings
    image: md5lukas/drone-mvn-settings
    settings:
      servers:
        - id: woolgens-network
          username: woolgens-default
      serverSecrets:
        from_secret: MAVEN_SERVER_SECRETS
  - name: deploy
    image: maven
    commands:
      - mvn deploy -B -s settings.xml
